FROM postgres:latest

#let docker know to take the file from the folder and put it inside this directory below and whatever is present will get run when container comes up
COPY create_table.sql/docker-entrypoint-initdb.d/